apiVersion: "rbac.authorization.k8s.io/v1"
kind: "RoleBinding"
metadata:
  name: "spicedb-watch-service"
  labels:
    app.kubernetes.io/name: "spicedb"
    app.kubernetes.io/version: "example"
    app: "spicedb"
subjects:
  - kind: "ServiceAccount"
    name: "spicedb-dev"
roleRef:
  apiGroup: "rbac.authorization.k8s.io"
  kind: "Role"
  name: "watch-service"

