apiVersion: "v1"
kind: "Service"
metadata:
  name: "spicedb"
  labels:
    app.kubernetes.io/name: "spicedb"
    app.kubernetes.io/version: "example"
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "9090"
spec:
  type: LoadBalancer
  loadBalancerIP: "34.132.113.166"
  selector:
    app: "spicedb"
  ports:
    - name: "grpc"
      port: 50051
      protocol: "TCP"
      targetPort: 50051
    - name: "http"
      port: 8080
      protocol: "TCP"
      targetPort: 8080
    - name: "dispatch"
      port: 50053
      protocol: "TCP"
      targetPort: 50053
    - name: "prometheus"
      port: 9090
      protocol: "TCP"
      targetPort: 9090

